// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYhvfuSyZP3fpDW4vG6QO_58k83_iL-_c',
    appId: '1:899726853186:web:060d9255863b8370ab99db',
    messagingSenderId: '899726853186',
    projectId: 'reminder-app-d165d',
    authDomain: 'reminder-app-d165d.firebaseapp.com',
    storageBucket: 'reminder-app-d165d.firebasestorage.app',
    measurementId: 'G-13K6H9147H',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxqS_3B9P8HhQD0s96Y0zjAGtaN-jfvzI',
    appId: '1:899726853186:ios:3f7ade4d0ec64e59ab99db',
    messagingSenderId: '899726853186',
    projectId: 'reminder-app-d165d',
    storageBucket: 'reminder-app-d165d.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxqS_3B9P8HhQD0s96Y0zjAGtaN-jfvzI',
    appId: '1:899726853186:ios:3f7ade4d0ec64e59ab99db',
    messagingSenderId: '899726853186',
    projectId: 'reminder-app-d165d',
    storageBucket: 'reminder-app-d165d.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYhvfuSyZP3fpDW4vG6QO_58k83_iL-_c',
    appId: '1:899726853186:web:1ba55e5212d6cdd5ab99db',
    messagingSenderId: '899726853186',
    projectId: 'reminder-app-d165d',
    authDomain: 'reminder-app-d165d.firebaseapp.com',
    storageBucket: 'reminder-app-d165d.firebasestorage.app',
    measurementId: 'G-YZP58ZFE9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmRw2RNL_GVPbcgdqCx16k7sGQtYfPZYs',
    appId: '1:899726853186:android:11746cbaa4514431ab99db',
    messagingSenderId: '899726853186',
    projectId: 'reminder-app-d165d',
    storageBucket: 'reminder-app-d165d.firebasestorage.app',
  );

}